# Generated by Django 6.0.5 on 2026-05-10 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('habit_completed', 'Habit Completed'), ('transaction_created', 'Transaction Created'), ('goal_updated', 'Goal Updated'), ('ai_warning', 'AI Warning'), ('productivity_update', 'Productivity Update')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_a_timesta_5b28a8_idx'), models.Index(fields=['event_type'], name='analytics_a_event_t_3356bb_idx')],
            },
        ),
    ]
