# Generated by Django 6.0.5 on 2026-05-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='analytics_a_timesta_5b28a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='analytics_a_event_t_3356bb_idx',
        ),
    ]
